# Analysis of GOP Donor Movements After Rubio and Bush Drop-outs

In [1]:
import pandas as pd
import datetime as dt

## Load and Find Candidate Committees

In [2]:
cn_headers = open("../data/cn_header_file.csv").read().strip().split(',')

In [6]:
# Added by Steve

open('../data/cn_header_file.csv').read()

'CAND_ID,CAND_NAME,CAND_PTY_AFFILIATION,CAND_ELECTION_YR,CAND_OFFICE_ST,CAND_OFFICE,CAND_OFFICE_DISTRICT,CAND_ICI,CAND_STATUS,CAND_PCC,CAND_ST1,CAND_ST2,CAND_CITY,CAND_ST,CAND_ZIP\n'

In [7]:
campaigns_to_commitees = pd.read_csv("../data/cn.txt", sep="|", names=cn_headers)

In [8]:
# Added by Steve
pd.read_csv('../data/cn.txt', sep='|')

,H0AK00097,"COX, JOHN R.",REP,2014,AK,H,00,C,N,C00525261,P.O. BOX 1092,Unnamed: 11,ANCHOR POINT,AK.1,99556
0,H0AL02087,"ROBY, MARTHA",REP,2016,AL,H,2.0,I,C,C00462143,PO BOX 195,NaN,MONTGOMERY,AL,36101.0
1,H0AL02095,"JOHN, ROBERT E JR",IND,2016,AL,H,2.0,C,N,NaN,1465 W OVERBROOK RD,NaN,MILLBROOK,AL,36054.0
2,H0AL05049,"CRAMER, ROBERT E ""BUD"" JR",DEM,2008,AL,H,5.0,C,P,C00239038,PO BOX 2621,NaN,HUNTSVILLE,AL,35804.0
3,H0AL05163,"BROOKS, MO",REP,2016,AL,H,5.0,I,C,C00464149,7610 FOXFIRE DRIVE,NaN,HUNTSVILLE,AL,35802.0
4,H0AL06088,"COOKE, STANLEY KYLE",REP,2010,AL,H,6.0,C,N,C00464222,723 CHERRY BROOK ROAD,NaN,KIMBERLY,AL,35091.0
5,H0AL07086,"SEWELL, TERRYCINA ANDREA",DEM,2016,AL,H,7.0,I,C,C00458976,PO BOX 1964,NaN,BIRMINGHAM,AL,35201.0
6,H0AL07094,"HILLIARD, EARL FREDERICK JR",DEM,2010,AL,H,7.0,O,P,C00460410,PO BOX 12804,NaN,BIRMINGHAM,AL,35202.0
7,H0AL07177,"CHAMBERLAIN, DON",REP,2012,AL,H,7.0,C,P,C00482059,512 LAPSLEY ST,NaN,SELMA,AL,36701.0
8,H0AR01083,"CRAWFORD, ERIC ALAN RICK",REP,2016,AR,H,1.0,I,C,C00462374,34 CR 455,NaN,JONESBORO,AR,72404.0
9,H0AR01091,"GREGORY, JAMES CHRISTOPHER",DEM,2010,AR,H,1.0,O,N,C00472126,510 S LILLY ST,NaN,BLYTHEVILLE,AR,72315.0
10,H0AR01109,"CAUSEY, CHAD",DEM,2010,AR,H,1.0,O,P,C00475384,205 SOUTH MAIN #203,NaN,JONESBORO,AR,72401.0
11,H0AR01125,"SMITH, PRINCELLA D",REP,2010,AR,H,1.0,O,P,C00480905,2000 WYNRIDGE COVE,NaN,WYNNE,AR,72396.0
12,H0AR02107,"GRIFFIN, JOHN TIMOTHY",REP,2014,AR,H,2.0,C,P,C00468116,P.O. BOX 7526,NaN,LITTLE ROCK,AR,72217.0
13,H0AR02131,"ELLIOTT, JOYCE ANN",DEM,2010,AR,H,2.0,O,P,C00475764,1715 FAIR PARK BLVD,NaN,LITTLE ROCK,AR,72204.0
14,H0AR03022,"SKOCH, BERNARD KURT 'BERNIE'",REP,2010,AR,H,3.0,O,P,NaN,21142 KIRKSEY ROAD,NaN,ELKINS,AR,72727.0
15,H0AR03030,"WHITAKER, DAVID JEFFREY",DEM,2010,AR,H,3.0,O,P,C00468033,PO BOX 957,NaN,FAYETTEVILLE,AR,727020957.0
16,H0AR03055,"WOMACK, STEVE",REP,2016,AR,H,3.0,I,C,C00477745,134 N PLEASANT RIDGE DRIVE,NaN,ROGERS,AR,727560701.0
17,H0AS00018,"FALEOMAVAEGA, ENI",DEM,2014,AS,H,0.0,C,P,C00231092,PO BOX 44669,NaN,WASHINGTON,DC,20026.0
18,H0AZ01184,"FLAKE, JEFF MR.",REP,2012,AZ,H,6.0,C,P,C00347260,4222 E MCLELLAN CIRCLE,UNIT 19,MESA,AZ,852053119.0
19,H0AZ01259,"GOSAR, PAUL ANTHONY",REP,2016,AZ,H,4.0,I,C,C00461806,PO BOX 2967,NaN,PRESCOTT,AZ,86302.0
20,H0AZ01283,"MEHTA, STEVE",REP,2010,AZ,H,1.0,C,P,C00474940,1340 S JIMSON LOOP,NaN,SHOW LOW,AZ,85901.0
21,H0AZ01325,"TOBIN, ANDY HON.",REP,2014,AZ,H,1.0,C,P,C00550012,2532 NORTH 4TH STREET,NaN,FLAGSTAFF,AZ,860043712.0
22,H0AZ01333,"GRESSLEY, FORREST DAYL",REP,2010,AZ,H,1.0,C,N,C00481267,1545 E STIRRUP CT,NaN,GILBERT,AZ,85296.0
23,H0AZ03321,"PARKER, VERNON",REP,2014,AZ,H,9.0,C,P,C00541508,6161 NORTH 28TH PLACE,NaN,PHOENIX,AZ,85016.0
24,H0AZ03362,"QUAYLE, BEN",REP,2012,AZ,H,6.0,C,P,C00475863,10645 N TATUM BLVD 200-429,NaN,PHOENIX,AZ,85028.0
25,H0AZ03404,"SCOTT, BRIAN ALAN",IND,2010,AZ,H,3.0,O,N,C00478735,3207 W MANDALAY LANE,NaN,PHOENIX,AZ,85053.0
26,H0AZ03412,"BAKER, SCOTT",REP,2010,AZ,H,3.0,O,N,C00480053,3317 E BELL RD SUITE 101 #164,NaN,PHOENIX,AZ,85022.0
27,H0AZ04485,"HILL, BRIAN",IND,2010,AZ,H,4.0,C,N,C00472068,PO BOX 6013,NaN,PHOENIX,AZ,85005.0
28,H0AZ04493,"CONTRERAS, JANET L",REP,2010,AZ,H,4.0,C,P,C00474007,2929 W MALDONADO ROAD,NaN,PHOENIX,AZ,85041.0
29,H0AZ04501,"PENALOSA, JOSE LUIS JR",IND,2014,AZ,H,7.0,O,P,C00559179,55 EAST LEXINGTON AVENUE,NaN,PHOENIX,AZ,85012.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6595,S8NE00026,"EXON, J JAMES",DEM,1990,NE,S,0.0,C,P,C00088120,330 HART BUILDING,NaN,WASHINGTON,DC,20510.0
6596,S8NE00117,"JOHANNS, MICHAEL O",REP,2014,NE,S,0.0,C,P,C00439802,5555 SOUTH STREET SUITE 100,NaN,LINCOLN,NE,68506.0
6597,S8NE00133,"KLEEB, SCOTT MICHAEL",DEM,2008,NE,S,0.0,O,P,C00414656,1010 N DENVER AVE,NaN,HASTINGS,NE,68901.0
6598,S8NE00141,"MARVIN, LARRY",DEM,2014,NE,S,0.0,O,N,C00502542,635 NORTH MAIN STREET SUITE 202,NaN,FREMONT,NE,68025.0
6599,S8NH00139,"SWETT, KATRINA",DEM,2008,NH,S,0.0,C,P,C00431502,1 PUTNEY RD,NaN,BOW,NH,3304.0
6600,S8NH00147,"MARCHAND, STEVE",DEM,2008,NH,S,0.0,C,P,C00432674,117 CASS ST,NaN,PORTSMOUTH,NH,3801.0
6601,S8NH00162,"GIRARD, SHAWN PAUL",IND,2008,NH,S,0.0,C,N,C00437046,141 STANIELS ROAD,NaN,LOUDON,NH,3307.0
6602,S8NJ00012,"BELL, JEFFREY",REP,2018,NJ,S,0.0,NaN,F,C00558122,NaN,NaN,PALISADES PARK,NJ,NaN
6603,S8NJ00285,"SABRIN, MURRAY",REP,2014,NJ,S,0.0,C,P,C00557447,1500 PALISADE AVE APT 2F,NaN,FORT LEE,NJ,7024.0
6604,S8NJ00392,"ANDREWS, ROBERT E",DEM,2008,NJ,S,0.0,C,P,C00448654,215 FOURTH AVE,NaN,HADDON HEIGHTS,NJ,8035.0
6605,S8NJ00418,"BOSS, JEFF",IND,2014,NJ,S,0.0,C,N,C00567602,7002 BLVD EAST APT 26G,NaN,GUTTENBERG,NJ,7093.0
6606,S8NM00143,"HANNAN, JIM",DEM,2008,NM,S,0.0,O,N,C00434704,PO BOX 31042,NaN,SANTA FE,NM,87594.0
6607,S8NM00184,"UDALL, TOM",DEM,2020,NM,S,0.0,I,NaN,C00329896,PO BOX 1881,NaN,SANTA FE,NM,87504.0
6608,S8NM00192,"LEHRMAN, R LELAND",DEM,2008,NM,S,0.0,O,N,C00442145,163 OLD LAMY TRAIL,NaN,LAMY,NM,81540.0
6609,S8NY00082,"SCHUMER, CHARLES E",DEM,2016,NY,S,0.0,I,C,C00346312,192 LEXINGTON AVENUE SUITE 1001,NaN,NEW YORK,NY,10016.0
6610,S8OK00225,"WALLACE, STEPHEN P",IND,2010,OK,S,0.0,C,N,C00431320,6528 EAST 101ST D-1 #304,NaN,TULSA,OK,74133.0
6611,S8OR00207,"MERKLEY, JEFFREY ALAN",DEM,2020,OR,S,0.0,I,F,C00437277,1351 SE 114TH AVE,NaN,PORTLAND,OR,97216.0
6612,S8PA00130,"MURPHY, LARRY GENE",REP,2010,PA,S,0.0,C,N,C00459602,778 LEXINGTON DR,NaN,HERMITAGE,PA,16148.0
6613,S8SD00024,"PRESSLER, LARRY",IND,2014,SD,S,0.0,O,P,C00554519,5105 SOUTH ROLLING GREEN AVE,NaN,SIOUX FALLS,SD,57108.0
6614,S8TN00253,"LEWIS, DANIEL T",LIB,2008,TN,S,0.0,C,N,C00446773,611 BROOKSBORO TERRACE,NaN,NASHVILLE,TN,37217.0
6615,S8TX00269,"STRIPLING, RANDOLPH B RANDY",IND,2008,TX,S,0.0,C,N,C00446609,9704 BEAUCHAMP SQUARE,NaN,AUSTIN,TX,78729.0
6616,S8VA00222,"WRIGHT, ISHAH",OTH,2008,VA,S,0.0,O,N,C00435131,632 THOMAS ROAD,NaN,LYNCHBURG,VA,24502.0
6617,S8VA00230,"MODICA, JULIEN",DEM,2012,VA,S,0.0,O,P,C00494187,11951 FREEDOM DRIVE FLOOR 13,NaN,RESTON,VA,20190.0
6618,S8VA00255,"GILMORE, JAMES S (JIM) III",REP,2008,VA,S,0.0,O,P,C00441261,631 S WASHINGTON STREET,NaN,ALEXANDRIA,VA,22314.0
6619,S8VA00263,"MARSHALL, ROBERT G",REP,2012,VA,S,0.0,O,P,C00511956,PO BOX 422,NaN,MANASSAS,VA,20108.0
6620,S8VT00059,"MCMULLEN, JOHN A",REP,2004,VT,S,0.0,C,P,C00334029,130 SOUTH WILLARD STREET,NaN,BURLINGTON,VT,5401.0
6621,S8WA00186,"SENN, DEBORAH",DEM,2000,WA,S,0.0,C,P,C00345025,PO BOX 22034,NaN,SEATTLE,WA,98122.0
6622,S8WA00194,"CANTWELL, MARIA",DEM,2018,WA,S,0.0,I,F,C00349506,PO BOX 12740,NaN,SEATTLE,WA,98111.0
6623,S8WI00026,"FEINGOLD, RUSSELL DANA",DEM,2016,WI,S,0.0,C,C,C00578013,PO BOX 620061,NaN,MIDDLETON,WI,53562.0
6624,S8WI00158,"NEUMANN, MARK W",REP,2012,WI,S,0.0,O,P,C00501361,W330N6233 HASSLINGER DRIVE,NaN,NASHOTAH,WI,53058.0

In [16]:
CAND_NAMES = [
    "KASICH, JOHN R",
    "TRUMP, DONALD J",
    "RUBIO, MARCO",
    "BUSH, JEB",
    'CRUZ, RAFAEL EDWARD "TED"'
]

In [17]:
COMMITTEE_IDS = campaigns_to_commitees[
    (campaigns_to_commitees["CAND_OFFICE"] == "P") &
    (campaigns_to_commitees["CAND_PTY_AFFILIATION"] == "REP") &
    (campaigns_to_commitees["CAND_ELECTION_YR"] == 2016) &
    (campaigns_to_commitees["CAND_NAME"].isin(CAND_NAMES))
].set_index("CAND_NAME")["CAND_PCC"].to_dict()
COMMITTEE_IDS

{'KASICH, JOHN R': 'C00581876',
 'CRUZ, RAFAEL EDWARD "TED"': 'C00574624',
 'RUBIO, MARCO': 'C00458844',
 'BUSH, JEB': 'C00579458',
 'TRUMP, DONALD J': 'C00580100'}

## Load and Clean Individual Donations

BuzzFeed News downloaded the "Contributions by Individuals" master file from the [FEC's website](http://www.fec.gov/finance/disclosure/ftpdet.shtml) on April 25, 2016. It contains information about every single itemized individual donation for every single 2016 campaign for contributors who have given more than $200 to a committee during this election cycle. You can download a copy of that data [here](https://archive.org/details/fec-contributions-master-file-2016-04-25).

First we select only the donations to the five Republican campaign committees we're interested in analyzing.

Then, we simplify each donor's name (removing suffixes and middle names, which committees have different approaches to reporting) and ZIP code (to the first five digits).

FEC campaign filings do not assign any unique identifiers to donors. So finally, to be able to distinguish and track individual donors, the code below assigns each contribution a `donor_uid` based on the donor's first name, last name, and ZIP code. This approach could result in an undercount of donors if, for instance, there are two people named John Smith in a same ZIP code — but should result in good approximations for the analyses below.

### Load All Itemized Individual Donations

In [18]:
ind_headers = open("../data/indiv_header_file.csv").read().strip().split(',')

In [19]:
# Added by Steve
ind_headers

['CMTE_ID',
 'AMNDT_IND',
 'RPT_TP',
 'TRANSACTION_PGI',
 'IMAGE_NUM',
 'TRANSACTION_TP',
 'ENTITY_TP',
 'NAME',
 'CITY',
 'STATE',
 'ZIP_CODE',
 'EMPLOYER',
 'OCCUPATION',
 'TRANSACTION_DT',
 'TRANSACTION_AMT',
 'OTHER_ID',
 'TRAN_ID',
 'FILE_NUM',
 'MEMO_CD',
 'MEMO_TEXT',
 'SUB_ID']

In [20]:
dtypes = {
    "NAME": str,
    "ZIP_CODE": str,
    "TRANSACTION_DT": str,
    "FILE_NUM": str,
    "MEMO_CD": str,
    "MEMO_TXT": str
}

In [21]:
donors = pd.read_csv(
    "../data/itcont.txt",
    sep="|", 
    names=ind_headers,
    dtype=dtypes
)

In [13]:
donors.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00004606,N,M4,P,15951124869,15,IND,"ARNOLD, ROBERT",MCPHERSON,KS,...,SELF,OPTOMETRIST,03102015,1000,NaN,SA11AI.20747,1002259,NaN,NaN,4041320151241796098
1,C00004606,N,M4,P,15951124869,15,IND,"BICKLE, DON",HAYS,KS,...,RETIRED,RETIRED,03302015,1000,NaN,SA11AI.20772,1002259,NaN,NaN,4041320151241796099
2,C00004606,N,M4,P,15951124869,15,IND,"ROSSMAN, RICHARD",OLATHE,KS,...,CRAWFORD SALES COMPANY,BUSINESSMAN,03302015,250,NaN,SA11AI.20759,1002259,NaN,NaN,4041320151241796100
3,C00452383,N,M4,P,15951124897,15,IND,"LLEWELLYN, CHARLES",FREDERICK,MD,...,NaN,NaN,03112015,500,NaN,SA11AI.25088,1002261,NaN,NaN,4041320151241796102
4,C00452383,N,M4,P,15951124897,15,IND,"TYNES, TIMOTHY MR.",VERO BEACH,FL,...,NaN,NaN,03022015,250,NaN,SA11AI.25074,1002261,NaN,NaN,4041320151241796103

In [22]:
gop_primary_donors = donors[
    donors["CMTE_ID"].isin(COMMITTEE_IDS.values()) &
    (donors["TRANSACTION_PGI"] == "P")
].copy()

### Clean Up Donation Data

In [24]:
def parse_date(date_string):
    if pd.isnull(date_string):
        return None
    else:
        return dt.datetime.strptime(date_string.strip(), "%m%d%Y")

In [25]:
gop_primary_donors["date"] = gop_primary_donors["TRANSACTION_DT"].apply(parse_date)

In [26]:
def extract_last_first(name):
    return " ".join(name.split(" ")[:2])

In [27]:
gop_primary_donors["last_first"] = gop_primary_donors["NAME"].apply(extract_last_first)
gop_primary_donors["zip_first_five"] = gop_primary_donors["ZIP_CODE"].fillna("").apply(lambda x: x[:5])

In [28]:
# Added by Steve
gop_primary_donors[['ZIP_CODE', 'zip_first_five']].head()

        ZIP_CODE zip_first_five
18207  760282217          76028
18208  597112904          59711
18209  294927523          29492
18210  772190630          77219
18211  331566023          33156

In [29]:
def make_uid(row):
    if pd.isnull(row["last_first"]) or (row["zip_first_five"] == ""):
        return None
    else:
        return "|".join([row["last_first"], row["zip_first_five"]])

In [30]:
gop_primary_donors["donor_uid"] = gop_primary_donors.apply(lambda x: make_uid(x), axis=1)

## Analyze the Data

The code below uses `donor_uid` to find the donors who made their first donation to a campaign committee after Jeb Bush and Marco Rubio dropped out of the 2016 Republican presidential primary—Feb. 20, 2016 and March 3, 2016 respectively. It then counts how many of those donations were made by donors who had previously given to the Bush or Rubio campaigns.

In [43]:
# This method aggregates total donations, by contributor and committee, 
# before and after a given date
def calculate_movements(since_date):
    grp = gop_primary_donors.groupby([
        # (Steve) group by unique donor
        "donor_uid",
        # (Steve) group by unique donor
        gop_primary_donors["date"] > since_date,
        "CMTE_ID",
    ])
    total_contribs = grp["TRANSACTION_AMT"].sum()
    return total_contribs.unstack().unstack().fillna(0)

In [44]:
calculate_movements("2016-02-20").head()

CMTE_ID                C00458844       C00574624       C00579458        \
date                       False True      False True      False True
donor_uid
AANONSEN, PAUL|20009         0.0   0.0       0.0   0.0       0.0   0.0
AARNIO, TERRANCE|97267       0.0   0.0       0.0   0.0    2700.0   0.0
AARON, CHARLES|91361         0.0   0.0     250.0   0.0       0.0   0.0
AARON, DAVID|30125           0.0   0.0       0.0   0.0       0.0   0.0
AARON, FRED|34240          200.0   0.0       0.0   0.0       0.0   0.0

CMTE_ID                C00580100        C00581876
date                       False  True      False True
donor_uid
AANONSEN, PAUL|20009       323.0    0.0       0.0   0.0
AARNIO, TERRANCE|97267       0.0    0.0       0.0   0.0
AARON, CHARLES|91361         0.0    0.0       0.0   0.0
AARON, DAVID|30125         253.0  303.0       0.0   0.0
AARON, FRED|34240            0.0    0.0       0.0   0.0

In [42]:
# Added by Steve
gop_primary_donors.groupby([
    'donor_uid',
    gop_primary_donors['date'] > '2016-02-20',
    "CMTE_ID"
])['TRANSACTION_AMT'].sum()

donor_uid                date   CMTE_ID
AANONSEN, PAUL|20009     False  C00580100     323
AARNIO, TERRANCE|97267   False  C00579458    2700
AARON, CHARLES|91361     False  C00574624     250
AARON, DAVID|30125       False  C00580100     253
                         True   C00580100     303
AARON, FRED|34240        False  C00458844     200
AARON, JOHN|23238        False  C00574624     200
                         True   C00574624     250
AARON, JONATHAN|48304    False  C00458844    2700
AARON, MARCIA|90266      True   C00581876    1000
AARON, MARTIN|77005      False  C00574624     500
AARONSON, JEFFREY|75201  False  C00581876     500
AARSBY, J.|57701         False  C00574624    1400
AARSHEIM, KNUTE|02738    False  C00579458     250
ABADI, MICHAEL|33180     False  C00579458    2500
ABAJIAN, KIM|93103       False  C00579458    2700
ABAJIAN, TED|93103       False  C00458844     620
                                C00579458    2700
ABARE, WILLIAM|32080     False  C00579458    1000
ABATE, JOSEPH|85004      False  C00579458     250
ABBE, ROSS|98225         False  C00574624     400
ABBINANTI, BECKY|60506   False  C00580100     267
ABBOTT, CHARLES|32210    False  C00458844     800
ABBOTT, DIANE|78613      False  C00574624     200
ABBOTT, G.|01983         False  C00574624    1000
ABBOTT, JEROME|75248     False  C00574624    2000
ABBOTT, JERRY|78516      False  C00580100     207
ABBOTT, JOSH|78735       False  C00458844    2700
ABBOTT, LARRY|43220      False  C00581876    2700
ABBOTT, LILIAN|77598     False  C00574624     750
                                             ...
ZURICH, BARBARA|61816    True   C00574624     249
ZURIFF, BRYAN|90049      False  C00458844    2000
ZURIFF, LAURENCE|10128   False  C00458844    2700
                                C00579458    2700
ZURN, DENISE|55416       False  C00574624     250
ZUROVEC, ROBERT|78642    False  C00574624     250
ZUSCHLAG, ELAINE|70508   False  C00579458    2700
ZUSCHLAG, RICHARD|70508  False  C00579458    2700
ZUST, KENNETH|90503      False  C00458844     250
ZUSY, CATHERINE|02139    True   C00581876     500
ZUTZ, PAUL|92211         False  C00579458     250
ZUZIK, MAXINE|15650      False  C00574624     500
ZUZUL, MIOMIR|20007      False  C00579458    1000
ZVONKOVIC, ALAN|06825    True   C00574624     500
ZVONOV, VLADIMIR|55378   True   C00574624     300
ZWAHLEN, RENE|35811      False  C00574624    1000
                         True   C00574624     500
ZWEIBACK, C.|91103       False  C00458844     700
ZWEIBACK, MARISA|91103   False  C00458844    2700
ZWEIBACK, MICHAEL|91103  False  C00458844    2000
ZWELLING, MARCY|90720    False  C00458844    1000
ZWICK, ANDREW|33140      False  C00458844    2400
ZWICK, MARCIA|10018      False  C00458844     250
ZWICK, PAUL|08319        False  C00574624     250
ZWIGARD, BRADLEY|33156   False  C00574624     900
ZWIGARD, BRIAN|33156     False  C00574624    3200
ZWIRKOSKI, GORDON|60074  True   C00574624     250
ZYLSTRA, ROBERT|50219    True   C00581876    1000
ZYLSTRA, THOMAS|51249    False  C00574624     250
ZYNDA, STEPHEN|48895     False  C00581876    2700
Name: TRANSACTION_AMT, Length: 86363, dtype: int64

In [45]:
def select_movements(from_candidate, to_candidate, since_date):
    movements = calculate_movements(since_date)
    return movements[
        # (steve) contributed to from-candidate > 0 before dropout
        (movements[(COMMITTEE_IDS[from_candidate], False)] > 0) &
        # (steve) contributions to to-candidate = 0 before dropout
        (movements[(COMMITTEE_IDS[to_candidate], False)] == 0) &
        # (steve) contributions to to-candidate > 0 after dropout
        (movements[(COMMITTEE_IDS[to_candidate], True)] > 0)
    ][(COMMITTEE_IDS[to_candidate], True)]

*Added by Steve* 

The `select_movements` function really identifies donors who donated to a new candidate for the first time after a candidate they previous donated to dropped out of the race. This seems like a very good way of detecting how donors "changed horses" in the middle of the race. For example, looking at who threw support to Kashich after Rubio:

**What counts**

| donor | before drop? | candidate |
| ----- | ------------ | --------- |
| a     | True         | Rubio     |
| a     | False        | Kasich    |

and this

| donor | before drop? | candidate |
| ----- | ------------ | --------- |
| b     | True         | Rubio     |
| b     | False        | Kasich    |
| b     | False        | Cruz      |


**What doesn't count** 

Donors can't have donated to the new candidate before the drop date

| donor | before drop? | candidate |
| ----- | ------------ | --------- |
| c     | True         | Rubio     |
| c     | True         | Kasich    |
| c     | False        | Kasich    |

In [51]:
# added by Steve, Rubio to Trump

kas_mv = calculate_movements('2016-02-20')
kas_mv[
    (kas_mv[(COMMITTEE_IDS['RUBIO, MARCO'], False)] > 0) 
]

CMTE_ID                     C00458844         C00574624         C00579458  \
date                            False   True      False   True      False
donor_uid
AARON, FRED|34240               200.0     0.0       0.0     0.0       0.0
AARON, JONATHAN|48304          2700.0     0.0       0.0     0.0       0.0
ABAJIAN, TED|93103              620.0     0.0       0.0     0.0    2700.0
ABBOTT, CHARLES|32210           800.0     0.0       0.0     0.0       0.0
ABBOTT, JOSH|78735             2700.0     0.0       0.0     0.0       0.0
ABBOTT, MARYANN|29609           300.0     0.0       0.0     0.0       0.0
ABBOTT, MATTHEW|02043          2700.0     0.0       0.0     0.0       0.0
ABDALLAH, RANDALL|48226        1000.0     0.0       0.0     0.0       0.0
ABDELKADER, ABDELGAWA|33765    1000.0     0.0       0.0     0.0       0.0
ABDELKADER, ATIF|33765         2700.0     0.0       0.0     0.0       0.0
ABELITE, ED|95138               250.0     0.0       0.0     0.0       0.0
ABELL, JAMES|20782              250.0   300.0       0.0     0.0       0.0
ABERBACH, SUSAN|10075          2700.0     0.0       0.0     0.0       0.0
ABERNATHY, WAYNE|22033         2500.0     0.0       0.0  2500.0       0.0
ABERS, ANNA|90292              2300.0     0.0     200.0     0.0       0.0
ABERS, ROBERT|90292            2700.0     0.0       0.0     0.0       0.0
ABONY, LORNE|78701             2700.0     0.0       0.0     0.0       0.0
ABOUAF, KEITH|90066             250.0     0.0       0.0     0.0       0.0
ABOUSSIE, KAMELA|75201         2700.0     0.0       0.0     0.0       0.0
ABOUSSIE, KENNETH|75201        1700.0     0.0       0.0     0.0       0.0
ABOUSSIE, KENNETH|75205        1000.0     0.0       0.0     0.0       0.0
ABRAHAM, MATTHEW|30507          500.0     0.0       0.0     0.0       0.0
ABRAHAMSON, RICK|45140         2700.0     0.0       0.0     0.0       0.0
ABRAMOWITZ, KENNETH|06890      2700.0     0.0   14400.0     0.0    3700.0
ABRAMOWITZ, NIRA|06890         1000.0     0.0    7100.0     0.0    2800.0
ABRAMS, ALLAN|33484            1500.0     0.0       0.0     0.0       0.0
ABRAMS, JACOB|10031             250.0     0.0       0.0     0.0       0.0
ABRAMS, ROBERT|10013            450.0     0.0     750.0     0.0       0.0
ABRAMS, ROBERT|10560            200.0     0.0       0.0     0.0       0.0
ABRAMS, STANLEY|90067          1000.0     0.0       0.0     0.0       0.0
...                               ...     ...       ...     ...       ...
ZONIES, ROBERT|34250           1000.0     0.0       0.0     0.0       0.0
ZOOK, SUSAN|20001              1000.0     0.0       0.0     0.0       0.0
ZORICH, BARBARA|77024          2700.0     0.0       0.0     0.0       0.0
ZORICH, ROBERT|77024           2700.0     0.0       0.0     0.0       0.0
ZORNIGER, FRANK|45429           300.0     0.0       0.0     0.0       0.0
ZOROYA, ALLEN|90065             200.0   216.0       0.0     0.0       0.0
ZORRILLA, JOSE|89135           2700.0     0.0       0.0     0.0       0.0
ZOUSMER, MICHAEL|48302         2700.0     0.0       0.0     0.0       0.0
ZOUSMER, STACY|48302           2700.0     0.0       0.0     0.0       0.0
ZUBAK, JOHN|18902               250.0     0.0       0.0     0.0       0.0
ZUBLER, TODD|22207             1000.0  1000.0       0.0     0.0       0.0
ZUBRIN, ROBERT|80401           1500.0     0.0       0.0     0.0       0.0
ZUCCARI, ALAN|22102            2700.0     0.0       0.0     0.0       0.0
ZUCCARI, LISA|22102            2700.0     0.0       0.0     0.0       0.0
ZUCKERMAN, IVAN|33156          1000.0     0.0    4000.0  -300.0       0.0
ZUCKERMAN, JEFFREY|20902       1000.0     0.0       0.0     0.0       0.0
ZUEHLKE, WAYNE|55127            500.0     0.0       0.0     0.0       0.0
ZULKA, ROBERT|90638             250.0     0.0       0.0     0.0       0.0
ZULOAGA, GUILLERMO|33158       2500.0   500.0       0.0     0.0       0.0
ZUMARRAGA, CARLOS|33019         450.0     0.0       0.0     0.0       0.0
ZUNIGA, ELIZABETH|33023        2500.0     0.0       0.0     0.0       0.0
ZURIFF, BRYAN|90049            2000.0     0.0       0.0     0.0       0.0
ZURIFF, LAURENCE|10128         2700.0     0.0       0.0     0.0    2700.0
ZUST, KENNETH|90503             250.0     0.0       0.0     0.0       0.0
ZWEIBACK, C.|91103              700.0     0.0       0.0     0.0       0.0
ZWEIBACK, MARISA|91103         2700.0     0.0       0.0     0.0       0.0
ZWEIBACK, MICHAEL|91103        2000.0     0.0       0.0     0.0       0.0
ZWELLING, MARCY|90720          1000.0     0.0       0.0     0.0       0.0
ZWICK, ANDREW|33140            2400.0     0.0       0.0     0.0       0.0
ZWICK, MARCIA|10018             250.0     0.0       0.0     0.0       0.0

CMTE_ID                           C00580100       C00581876
date                        True      False True      False  True
donor_uid
AARON, FRED|34240             0.0       0.0   0.0       0.0    0.0
AARON, JONATHAN|48304         0.0       0.0   0.0       0.0    0.0
ABAJIAN, TED|93103            0.0       0.0   0.0       0.0    0.0
ABBOTT, CHARLES|32210         0.0       0.0   0.0       0.0    0.0
ABBOTT, JOSH|78735            0.0       0.0   0.0       0.0    0.0
ABBOTT, MARYANN|29609         0.0       0.0   0.0       0.0    0.0
ABBOTT, MATTHEW|02043         0.0       0.0   0.0       0.0    0.0
ABDALLAH, RANDALL|48226       0.0       0.0   0.0       0.0    0.0
ABDELKADER, ABDELGAWA|33765   0.0       0.0   0.0       0.0    0.0
ABDELKADER, ATIF|33765        0.0       0.0   0.0       0.0    0.0
ABELITE, ED|95138             0.0       0.0   0.0       0.0    0.0
ABELL, JAMES|20782            0.0       0.0   0.0       0.0    0.0
ABERBACH, SUSAN|10075         0.0       0.0   0.0       0.0    0.0
ABERNATHY, WAYNE|22033        0.0       0.0   0.0       0.0    0.0
ABERS, ANNA|90292             0.0       0.0   0.0       0.0    0.0
ABERS, ROBERT|90292           0.0       0.0   0.0       0.0    0.0
ABONY, LORNE|78701            0.0       0.0   0.0       0.0    0.0
ABOUAF, KEITH|90066           0.0       0.0   0.0       0.0    0.0
ABOUSSIE, KAMELA|75201        0.0       0.0   0.0       0.0    0.0
ABOUSSIE, KENNETH|75201       0.0       0.0   0.0       0.0    0.0
ABOUSSIE, KENNETH|75205       0.0       0.0   0.0       0.0    0.0
ABRAHAM, MATTHEW|30507        0.0       0.0   0.0       0.0    0.0
ABRAHAMSON, RICK|45140        0.0       0.0   0.0       0.0    0.0
ABRAMOWITZ, KENNETH|06890     0.0       0.0   0.0       0.0    0.0
ABRAMOWITZ, NIRA|06890        0.0       0.0   0.0       0.0    0.0
ABRAMS, ALLAN|33484           0.0       0.0   0.0       0.0    0.0
ABRAMS, JACOB|10031           0.0       0.0   0.0       0.0    0.0
ABRAMS, ROBERT|10013          0.0       0.0   0.0       0.0    0.0
ABRAMS, ROBERT|10560          0.0       0.0   0.0       0.0    0.0
ABRAMS, STANLEY|90067         0.0       0.0   0.0       0.0    0.0
...                           ...       ...   ...       ...    ...
ZONIES, ROBERT|34250          0.0       0.0   0.0       0.0    0.0
ZOOK, SUSAN|20001             0.0       0.0   0.0       0.0    0.0
ZORICH, BARBARA|77024         0.0       0.0   0.0       0.0    0.0
ZORICH, ROBERT|77024          0.0       0.0   0.0       0.0    0.0
ZORNIGER, FRANK|45429         0.0       0.0   0.0     250.0  500.0
ZOROYA, ALLEN|90065           0.0       0.0   0.0       0.0    0.0
ZORRILLA, JOSE|89135          0.0       0.0   0.0       0.0    0.0
ZOUSMER, MICHAEL|48302        0.0       0.0   0.0       0.0    0.0
ZOUSMER, STACY|48302          0.0       0.0   0.0       0.0    0.0
ZUBAK, JOHN|18902             0.0       0.0   0.0       0.0    0.0
ZUBLER, TODD|22207            0.0       0.0   0.0       0.0    0.0
ZUBRIN, ROBERT|80401          0.0       0.0   0.0       0.0    0.0
ZUCCARI, ALAN|22102           0.0       0.0   0.0       0.0    0.0
ZUCCARI, LISA|22102           0.0       0.0   0.0       0.0    0.0
ZUCKERMAN, IVAN|33156         0.0       0.0   0.0       0.0    0.0
ZUCKERMAN, JEFFREY|20902      0.0       0.0   0.0       0.0    0.0
ZUEHLKE, WAYNE|55127          0.0       0.0   0.0       0.0    0.0
ZULKA, ROBERT|90638           0.0       0.0   0.0       0.0    0.0
ZULOAGA, GUILLERMO|33158      0.0       0.0   0.0       0.0    0.0
ZUMARRAGA, CARLOS|33019       0.0       0.0   0.0       0.0    0.0
ZUNIGA, ELIZABETH|33023       0.0       0.0   0.0       0.0    0.0
ZURIFF, BRYAN|90049           0.0       0.0   0.0       0.0    0.0
ZURIFF, LAURENCE|10128        0.0       0.0   0.0       0.0    0.0
ZUST, KENNETH|90503           0.0       0.0   0.0       0.0    0.0
ZWEIBACK, C.|91103            0.0       0.0   0.0       0.0    0.0
ZWEIBACK, MARISA|91103        0.0       0.0   0.0       0.0    0.0
ZWEIBACK, MICHAEL|91103       0.0       0.0   0.0       0.0    0.0
ZWELLING, MARCY|90720         0.0       0.0   0.0       0.0    0.0
ZWICK, ANDREW|33140           0.0       0.0   0.0       0.0    0.0
ZWICK, MARCIA|10018           0.0       0.0   0.0       0.0    0.0

[19724 rows x 10 columns]

In [46]:
REMAINING_CANDIDATES = [
    'CRUZ, RAFAEL EDWARD "TED"',
    "KASICH, JOHN R",
    "TRUMP, DONALD J" 
]

DROPOUTS = [ 
    ("BUSH, JEB", "2016-02-20"), 
    ("RUBIO, MARCO", "2016-03-15") 
]

In [47]:
for cand_r in REMAINING_CANDIDATES:
    for cand_drop, date_drop in DROPOUTS:
        m = select_movements(cand_drop, cand_r, date_drop)
        print("{0} from {1}\n{2} donors\n${3:,.0f}\n".format(cand_r, cand_drop, len(m), m.sum()))

CRUZ, RAFAEL EDWARD "TED" from BUSH, JEB
63 donors
$99,710

CRUZ, RAFAEL EDWARD "TED" from RUBIO, MARCO
120 donors
$126,650

KASICH, JOHN R from BUSH, JEB
131 donors
$173,850

KASICH, JOHN R from RUBIO, MARCO
97 donors
$92,168

TRUMP, DONALD J from BUSH, JEB
9 donors
$13,817

TRUMP, DONALD J from RUBIO, MARCO
6 donors
$4,504

---

---

---